### ISSUE TITLE
LaTeXML for arXiv conversion?

### ISSUE THREAD

**Issue by dginev** [arxiv-vanity/engrafo#159]
> We couldn't find a good LaTeX to HTML converter.

Have you heard of / tried LaTeXML?
Repository: https://github.com/brucemiller/LaTeXML

My research group has been running latexml over arxiv for some time now, trying to improve coverage. Current results over arXiv are just short of 60% error-free on the dataset up-to 10.2017.
http://cortex.mathweb.org/corpus/arXMLiv/tex_to_html

We have been meaning to showcase our results better / had briefly experimented with the TeX.js typesetting project:
https://github.com/davidar/TeX.js

which worked relatively well. But our efforts were to a large degree stalled by the inability to redistribute the HTML results for the arXiv documents. Could I ask how you addressed the redistribution issue? (the default arXiv license is the main showstopper in this respect).

 Curious to see if we can find some synergies between the projects, such as seeing if latexml can be leveraged in engrafo, or whether we can use arxiv-vanity's presentation in our own cortex system. 

Just sending a signal flare that we are out there, since I was just forwarded your work today. Kudos!

**Comment by bfirsh** [comment]
I’m pretty sure we looked at that, but in the end we chose Pandoc for a reason I can’t remember. @andreasjansson do you remember?

(And sorry for the “couldn’t find a good converter dig”. ;) I meant one that not just output HTML, but also styled it nicely and made it work on mobile. It’s the same for pandoc.)

> But our efforts were to a large degree stalled by the inability to redistribute the HTML results for the arXiv documents. Could I ask how you addressed the redistribution issue? (the default arXiv license is the main showstopper in this respect).

We almost stopped because of the license, too. We went ahead for two reasons:

1) we’re just a converter, not “distributing” by some definition of distributing. It’s a bit like what those PDF reformatters are doing, or perhaps something like what Instapaper do. But IANAL. 
2) more practically, I don’t think anybody cares. The vast majority of authors seem really excited that their papers are available as web pages. We’ve had one complaint and we’ve offered to make it impossible to just redirect to the PDF instead of showing the conversion. And that was just because it was broken, so long term hopefully that’ll stop being a problem. ;)

Long-term, I’d really like for us to be integrated with arxiv somehow. In the same way they can review PDF renders, they could review the HTML render.

> Curious to see if we can find some synergies between the projects, such as seeing if latexml can be leveraged in engrafo, or whether we can use arxiv-vanity's presentation in our own cortex system.

For sure! I’d love for us to collaborate somehow. There’s no point duplicating work — I think we have the same end goal. We’ll reevaluate LaTeXML, and feel free to pinch whatever you like from our work.

**Comment by michal-h21** [comment]
I would also like to ask what problems did you find with `tex4ht`? It's output doesn't look great by default because of backwards compatibility, but you can request HTML5 and MathML output using simple command line switches. Almost every aspect of the generated HTML can be also changed using configuration files.

It uses actual LaTeX for conversion, so it supports most packages included in TeX distributions and custom macros.

**Comment by dginev** [comment]
Thanks for the heads up @bfirsh! Looking forward to the quick summary by @andreasjansson about which parts were unusable for the project. The most common concerns we've heard in the past have been 1) it's too slow or 2) Perl? Looks too old!

We're working on addressing both of those, but it's quite helpful to hear the considerations of sibling efforts, so that we improve in the right avenues. 

As to the licensing situation, thanks for the clarification! I guess you've decided to "run with it" assuming no one would care, and for the most part that is likely a very solid assumption if you're not attempting to replace arXiv in full - which clearly you aren't. Thanks again!

**Comment by bfirsh** [comment]
@dginev I must say that was my first reaction - "Perl?!"

To be honest, that isn't much better than Pandoc though. As much as we love it in theory, we're really struggling to use Haskell in practice. I imagine that would turn away a lot of other contributors too.

There is also the problem with Pandoc is that it is designed to be output in multiple formats. So it has this intermediate AST that is not as expressive as we like. It feels like we're shoehorning a lot of things in. Most of the post-processors are fixing things that Pandoc can't do.

If you're thinking of a rewrite in another language, we could potentially be interested in helping out. What are your plans? Or have you got a link to more details?

**Comment by bfirsh** [comment]
@dginev Also the fact your manual is a PDF made me laugh ;)

**Comment by dginev** [comment]
Hey, hey, the manual is both in PDF and HTML, exactly to demonstrate the duality :smiley:

The web version of the same manual is at the official site:
http://dlmf.nist.gov/LaTeXML/manual/

So we have all bases covered :+1:

**Comment by dginev** [comment]
Maybe this is the right time to mention we have two competing rewrite experiments under wraps, one remaining half-loyal to Perl and submerging the core processing in C, the other starting fresh in Rust (that's what I am personally working on). You may say that isn't mainstream enough and you would really prefer a Java or JavaScript rewrite, but so far that hasn't been sufficiently compelling. On the JavaScript front you don't really gain much performance over Perl, and our main rewrite motivation is exactly performance. On the other hand, switching to Java makes it quite difficult to maintain the flexibility and shortcuts we have been able to take with Perl's syntax and dynamic nature, so that feels very awkward as well. We still have an ongoing debate for better prog. lang targets.

But surprisingly to me, a Rust rewrite seems to be able to support a lot of the high level expressivity Perl does, keeps the programming model close enough, and is anywhere between 100x-10x faster, which is quite exciting. But it's still far from production-ready! LaTeXML's current implementation on the other hand is used in production somewhat widely by now, which makes it a solid foundation - similarly to Pandoc.

**Comment by bfirsh** [comment]
I agree, JavaScript is an awful language to write a converter in. The only reason bits of Engrafo are in JavaScript is because it has excellent libraries for manipulating web pages (jsdom, Distill, MathJax, etc). Even if the core of a converter were in a better language, I would imagine we would still need some kind of JS post-processor.

I have written an Adobe InDesign to HTML converter in Python in the past, and it was a delight. Python has all of the ease and expressiveness you describe, and a fantastic ecosystem of libraries.

But, I am enthusiastic about Rust. I think it would be a good language for this sort of thing, and I have been meaning to try it out.

FWIW, we don't care about performance. The vast majority of rendering time is spent converting/processing images. Manipulating strings/a DOM is negligible compared to that.

**Comment by brucemiller** [comment]
Forgive the eavesdropping; I'm the Perl+C proponent of LaTeXML, but am interested in opinions and options.  Javascript is non-starter. Python also; I can't buy into the things it restricts, and with things they don't restrict, it seems that many Python programmers manage to write just as sloppy as many Perl programmers. Perl certainly isn't as popular as it used to be, though.

The difficulty with languages like Rust and Java (or related like Scala) is that I see a need for a scripting component, not requiring compilation for minor tweaks, which adds a layer of complexity, and is then a 2nd language that you hope the community will buy into!
