### ISSUE TITLE
pandoc

### ISSUE THREAD

**Issue by isomorphisms** [arxiv-vanity/engrafo#263]
> We couldn't find a good LaTeX to HTML converter.

what was wrong with `pandoc`?

**Comment by asmaier** [comment]
I would like to add:

What was wrong with https://www-sop.inria.fr/marelle/tralics/ ? 
For example [Softcover.io](https://www.softcover.io/) is using it: https://github.com/softcover/tralics

**Comment by bfirsh** [comment]
@isomorphisms Pandoc is a long and complicated story!

In short: we started with Pandoc, and [spent a long time hacking it](https://github.com/arxiv-vanity/pandoc) to make it parse more than 10% of Arxiv papers. It is not designed as a serious LaTeX renderer. It can't parse most stuff, and it doesn't support packages or anything like that.

We spent 3 months getting Pandoc from ~10% to ~50% rendering (I am guessing at these percentages) at which point we released Arxiv Vanity. After launch, @dginev pointed us at LaTeXML which we had skipped over initially. Instantly we had ~75% of papers rendering reasonably well.

Hope that provides some clarity.

**Comment by bfirsh** [comment]
@asmaier Looks like it hasn't had a release in 10 years...

**Comment by dginev** [comment]
> We couldn't find a good LaTeX to HTML converter.

This phrase continues to stir up controversy... 😉

**Comment by bfirsh** [comment]
@dginev hahah, yes.

I mean, it’s true, we didn’t find one. But that was our own fault. And it is now an unfair statement. Perhaps it should be updated to “a latex to html converter with a good stylesheet” or something. ;)

**Comment by asmaier** [comment]
@bfirsh From the [webpage of tralics](https://www-sop.inria.fr/marelle/tralics/) (under Status of the Software):

> Current version is 2.15.4 released 25-november-2015; modfied 26-may-2017 

So saying that it didn't have a release for ten years is a bit strange. Tralics has one distinct advantage over latexml: It is written in C++ and should run much faster than latexml, which is developed in Perl.

**Comment by dginev** [comment]
> Tralics has one distinct advantage over latexml: It is written in C++ and should run much faster than latexml, which is developed in Perl.

Indeed, it is very significantly faster. Something that is very high on our priority list of enhancements in the latexml team, but we are nowhere near competitive right now. 

One thing I am curious of is whether the tralics coverage over arXiv has gone significantly up since the last time we measured it - which was now almost a decade ago! - https://eudml.org/doc/220017 Maybe something I could organize again in 2018, now that our [new build system](https://github.com/dginev/cortex) is somewhat robust. 

In fact, I could use some help with finding the "best practice" parameters for running both pandoc and tralics over arXiv, to ensure we are presenting coverage faithfully. Anyone here willing to join in and co-hack/co-analyze this? You may already know the perfect invocations for the two tools. Could be a peaceful background project, no tight deadlines etc.
